### ISSUE TITLE
unpickle files

### ISSUE THREAD

**Issue by l4nz8** [syahidhusein/ImageRecommender#2]
We need a function that unpacks and merges all created .pkl files,  to load them into a variable

**Comment by l4nz8** [comment]
ok i wrote a function (merge_pkls) in the save_load.py file with which you can manually merge two files. It would be good if we can still automate it.

**Comment by syahidhusein** [comment]
we already solved this issue by merging the pickle files and created the embedding arrays out of it. I will mark this as closed.
